Repository TabarakoAkula/ChtoZadano, pull requests merged in 2024-08, with the labels that each got.

#69 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/custom.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: enhancement

#70 Implemented info handler
  chtozadano/telegram_bot/handlers/help_handler.py
  chtozadano/telegram_bot/handlers/homework_handlers.py
Labels: enhancement, bot

#77 Server logger
  README.md
  chtozadano/chtozadano/settings.py
  chtozadano/gunicorn_config.py
  chtozadano/logs/.gitkeep
  docker-compose.yml
Labels: documentation, enhancement, server

#78 Remove Notebook and Server logger
  README.md
  chtozadano/chtozadano/settings.py
  chtozadano/gunicorn_config.py
  chtozadano/logs/.gitkeep
  docker-compose.yml
Labels: documentation, enhancement, To production

#80 [FIX] Cron scheduler
  cron/Dockerfile
  cron/cron_task
  cron/delete_old_hw_script.sh
  cron/script.sh
  docker-compose.yml
Labels: server, fix

#83 Server tests
  chtozadano/chtozadano/api.py
  chtozadano/fixtures/test_api_data.json
  chtozadano/homework/api/views.py
  chtozadano/homework/notifier.py
  chtozadano/homework/tests/test_api_homework.py
  chtozadano/homework/tests/test_static_url_homework.py
  chtozadano/users/api/views.py
  chtozadano/users/tests/test_api_users.py
  chtozadano/users/utils.py
  cron/Dockerfile
  cron/cron_task
  cron/delete_old_hw_script.sh
  cron/script.sh
  docker-compose.yml
Labels: S-tests, To production
